/* Flat list of every title key in src/lib/companies.ts's FRANCHISE_MAP --
   the seed list worker/backfill/deepRun.ts searches xREL for. A hand-synced
   derived copy, not a cross-directory import: worker/ and src/ bundle
   independently (wrangler vs. Vite, see worker/shared/constants.ts's own
   comment on why), same reason STARRED_GROUPS is duplicated there instead
   of imported. Only the title strings are needed here, not the franchise
   grouping itself, so this is a flat array, not the full map. Regenerate by
   hand (extract FRANCHISE_MAP's keys) whenever that map changes meaningfully
   -- staleness here only means a newly-added franchise entry doesn't get
   the deep-search treatment until this list is refreshed, not a correctness
   bug, since the frontend's own FRANCHISE_MAP is what actually drives
   display grouping regardless of what this backfill has reached so far. */
export const FRANCHISE_SEED_TITLES: string[] = [
  "assassin's creed black flag resynced",
  "assassin's creed shadows",
  "assassin's creed valhalla",
  "assassin's creed mirage",
  "assassin's creed odyssey",
  "assassin's creed origins",
  "assassin's creed syndicate",
  "assassin's creed unity",
  "assassin's creed rogue",
  "assassin's creed 4 black flag",
  "assassin's creed iii",
  "assassin's creed iii: remastered",
  "assassin's creed brotherhood",
  "assassin's creed revelations",
  "assassin's creed ii",
  "assassin's creed",
  "assassin's creed: liberation hd",
  "watch dogs",
  "watch dogs 2",
  "watch dogs: legion",
  "watch dogs legion",
  "far cry 6",
  "far cry 5",
  "far cry 4",
  "far cry 3",
  "far cry 3: blood dragon",
  "far cry primal",
  "far cry new dawn",
  "far cry 2",
  "far cry",
  "tom clancy's rainbow six siege",
  "tom clancy's rainbow six siege x",
  "tom clancy's rainbow six extraction",
  "tom clancy's rainbow six vegas",
  "tom clancy's rainbow six vegas 2",
  "tom clancy's the division",
  "tom clancy's the division 2",
  "tom clancy's ghost recon breakpoint",
  "tom clancy's ghost recon wildlands",
  "tom clancy's ghost recon future soldier",
  "tom clancy's splinter cell",
  "splinter cell",
  "tom clancy's splinter cell: chaos theory",
  "tom clancy's splinter cell: blacklist",
  "tom clancy's splinter cell: conviction",
  "prince of persia: the lost crown",
  "prince of persia: the sands of time remake",
  "prince of persia: the sands of time",
  "prince of persia: warrior within",
  "prince of persia: the two thrones",
  "prince of persia",
  "star wars outlaws",
  "just dance 2026",
  "just dance 2025",
  "for honor",
  "the crew motorfest",
  "the crew 2",
  "the crew",
  "anno 1800",
  "anno 117: pax romana",
  "trials rising",
  "trials fusion",
  "riders republic",
  "battlefield 6",
  "battlefield 2042",
  "battlefield v",
  "battlefield 1",
  "battlefield 4",
  "battlefield 3",
  "battlefield hardline",
  "battlefield: bad company 2",
  "need for speed unbound",
  "need for speed heat",
  "need for speed rivals",
  "need for speed payback",
  "need for speed most wanted",
  "the sims 4",
  "the sims 3",
  "the sims 2",
  "dead space",
  "dead space (2023)",
  "dead space 2",
  "dead space 3",
  "mass effect legendary edition",
  "mass effect: andromeda",
  "dragon age: the veilguard",
  "dragon age inquisition",
  "dragon age ii",
  "dragon age: origins",
  "star wars jedi: survivor",
  "star wars jedi: fallen order",
  "star wars jedi survivor",
  "star wars battlefront ii",
  "star wars battlefront",
  "ea sports fc 26",
  "ea sports fc 25",
  "ea sports fc 24",
  "fifa 23",
  "fifa 22",
  "fifa 21",
  "fifa 20",
  "fifa 19",
  "fifa 18",
  "fifa 17",
  "fifa 16",
  "fifa 15",
  "madden nfl 26",
  "madden nfl 25",
  "madden nfl 24",
  "madden nfl 23",
  "madden nfl 22",
  "madden nfl 21",
  "madden nfl 20",
  "ea sports college football 27",
  "ea sports college football 26",
  "ea sports college football 25",
  "ncaa football 14",
  "ncaa football 13",
  "ncaa football 12",
  "ncaa football 11",
  "ncaa football 10",
  "nhl 26",
  "nhl 25",
  "apex legends",
  "titanfall 2",
  "titanfall",
  "it takes two",
  "split fiction",
  "a way out",
  "unravel two",
  "unravel",
  "plants vs. zombies: garden warfare 2",
  "plants vs. zombies: garden warfare",
  "plants vs. zombies",
  "command & conquer remastered collection",
  "call of duty: modern warfare 4",
  "call of duty: black ops 7",
  "call of duty: black ops 6",
  "call of duty: modern warfare iii",
  "call of duty: modern warfare ii",
  "call of duty: warzone",
  "call of duty: black ops cold war",
  "call of duty: modern warfare",
  "call of duty: black ops 4",
  "call of duty: vanguard",
  "call of duty: wwii",
  "diablo iv",
  "diablo immortal",
  "diablo iii",
  "diablo ii: resurrected",
  "overwatch 2",
  "overwatch",
  "crash bandicoot 4: it's about time",
  "crash bandicoot n. sane trilogy",
  "spyro reignited trilogy",
  "world of warcraft",
  "starcraft ii",
  "starcraft: remastered",
  "hearthstone",
  "guitar hero live",
  "tony hawk's pro skater 1 + 2",
  "halo: the master chief collection",
  "halo infinite",
  "gears 5",
  "gears of war: e-day",
  "gears of war: reloaded",
  "forza motorsport",
  "forza horizon 5",
  "forza horizon 6",
  "age of empires iv",
  "age of empires ii: definitive edition",
  "sea of thieves",
  "minecraft",
  "grand theft auto v",
  "grand theft auto vi",
  "grand theft auto: the trilogy",
  "grand theft auto iv",
  "red dead redemption 2",
  "red dead redemption",
  "l.a. noire",
  "max payne 3",
  "max payne",
  "bioshock: the collection",
  "bioshock infinite",
  "borderlands 4",
  "borderlands 3",
  "borderlands 2",
  "borderlands: the pre-sequel",
  "borderlands: game of the year edition",
  "mafia: the old country",
  "mafia iii: definitive edition",
  "mafia: definitive edition",
  "mafia ii: definitive edition",
  "nba 2k26",
  "nba 2k25",
  "nba 2k24",
  "nba 2k23",
  "nba 2k22",
  "wwe 2k26",
  "wwe 2k25",
  "wwe 2k24",
  "wwe 2k23",
  "sid meier's civilization vii",
  "sid meier's civilization vi",
  "sid meier's civilization v",
  "xcom 2",
  "xcom: enemy unknown",
  "kerbal space program 2",
  "kerbal space program",
  "final fantasy vii rebirth",
  "final fantasy xvi",
  "final fantasy xiv online",
  "final fantasy vii remake intergrade",
  "final fantasy xv",
  "final fantasy vii",
  "kingdom hearts iii",
  "kingdom hearts hd 1.5 + 2.5 remix",
  "tomb raider",
  "shadow of the tomb raider",
  "rise of the tomb raider",
  "deus ex: mankind divided",
  "deus ex: human revolution",
  "dragon quest xi s",
  "dragon quest builders 2",
  "nier: automata",
  "nier replicant ver.1.22474487139...",
  "just cause 4",
  "just cause 3",
  "life is strange 2",
  "life is strange: true colors",
  "life is strange",
  "outriders",
  "resident evil 4",
  "resident evil village",
  "resident evil requiem",
  "resident evil 2",
  "resident evil 3",
  "resident evil 7 biohazard",
  "resident evil 5",
  "resident evil 6",
  "resident evil 0",
  "resident evil: revelations",
  "resident evil: revelations 2",
  "monster hunter wilds",
  "monster hunter rise",
  "monster hunter: world",
  "street fighter 6",
  "street fighter v",
  "devil may cry 5",
  "devil may cry 4 special edition",
  "dmc: devil may cry",
  "devil may cry hd collection",
  "mega man 11",
  "mega man legacy collection",
  "mega man x legacy collection",
  "mega man x legacy collection 2",
  "mega man zero/zx legacy collection",
  "dragon's dogma 2",
  "dragon's dogma: dark arisen",
  "phoenix wright: ace attorney trilogy",
  "the great ace attorney chronicles",
  "onimusha: warlords",
  "onimusha 2: samurai's destiny",
  "tekken 8",
  "tekken 7",
  "elden ring",
  "elden ring nightreign",
  "dark souls iii",
  "dark souls remastered",
  "dark souls ii",
  "dragon ball: sparking! zero",
  "dragon ball fighterz",
  "dragon ball xenoverse 2",
  "ace combat 7: skies unknown",
  "soulcalibur vi",
  "little nightmares ii",
  "little nightmares",
  "code vein",
  "the dark pictures anthology: house of ashes",
  "the elder scrolls v: skyrim",
  "the elder scrolls online",
  "the elder scrolls iv: oblivion",
  "the elder scrolls iii: morrowind",
  "fallout 4",
  "fallout 76",
  "fallout: london",
  "fallout: new vegas",
  "fallout 3",
  "doom: the dark ages",
  "doom eternal",
  "doom (2016)",
  "wolfenstein: the new colossus",
  "wolfenstein: the old blood",
  "wolfenstein: youngblood",
  "dishonored 2",
  "dishonored",
  "dishonored: death of the outsider",
  "starfield",
  "the witcher 3: wild hunt",
  "the witcher 4",
  "the witcher 2: assassins of kings",
  "cyberpunk 2077",
  "cyberpunk 2077: phantom liberty",
  "sonic x shadow generations",
  "sonic frontiers",
  "sonic generations",
  "sonic mania",
  "like a dragon: infinite wealth",
  "yakuza 0",
  "yakuza: like a dragon",
  "yakuza kiwami",
  "yakuza kiwami 2",
  "judgment",
  "total war: warhammer iii",
  "total war: pharaoh",
  "total war: warhammer ii",
  "total war: three kingdoms",
  "total war: rome ii",
  "football manager 26",
  "football manager 25",
  "football manager 24",
  "persona 5 royal",
  "persona 3 reload",
  "persona 4 golden",
  "batman: arkham knight",
  "batman: arkham city",
  "batman: arkham asylum",
  "batman: arkham origins",
  "mortal kombat 1",
  "mortal kombat 11",
  "lego batman: legacy of the dark knight",
  "lego star wars: the skywalker saga",
  "lego marvel super heroes",
  "lego marvel super heroes 2",
  "lego party!",
  "lego harry potter collection",
  "hogwarts legacy",
  "middle-earth: shadow of war",
  "middle-earth: shadow of mordor",
  "metal gear solid delta: snake eater",
  "metal gear solid v: the phantom pain",
  "metal gear solid v: ground zeroes",
  "metal gear solid: master collection vol. 1",
  "silent hill 2",
  "silent hill f",
  "efootball 2026",
  "pes 2021",
  "pes 2020",
  "007 first light",
  "hitman: world of assassination",
  "hitman 3",
  "hitman 2",
  "hitman (2016)",
  "pubg: battlegrounds",
  "cities: skylines ii",
  "cities: skylines",
  "crusader kings iii",
  "europa universalis v",
  "europa universalis iv",
  "stellaris",
  "hearts of iron iv",
  "a plague tale: requiem",
  "a plague tale: innocence",
  "saints row",
  "saints row iv",
  "saints row: the third",
  "dead island 2",
  "dead island",
  "metro exodus",
  "metro: last light redux",
  "metro 2033 redux",
  "celeste",
  "outer wilds",
  "palworld",
  "uncharted: legacy of thieves collection",
  "the last of us part ii remastered",
  "helldivers",
  "injustice",
  "injustice 2",
  "injustice: götter unter uns",
];
